---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude:
  (?x)( LICENSE| LICENSES/| pnpm-lock.yaml| ^\.github/styles/Microsoft/|
  .cspellcache )
ci:
  autofix_commit_msg: ðŸŽ¨ [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: â¬† [pre-commit.ci] pre-commit autoupdate
fail_fast: false

repos:
  # ----------------------------------------------------
  # 1. Trailing Whitespace and Line Endings
  # ----------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: mkdocs.yml
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key

  # ------------------------
  # Git / commit checks
  # ------------------------
  - repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.3
    hooks:
      - id: sync-pre-commit-deps

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # ------------------------
  # Taplo linting
  # ------------------------
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint

  # ------------------------
  # YAML linting
  # ------------------------
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: yamllint (general yaml)
        args: [-c, .yamllint]
        files: \.(yaml|yml)$
        exclude: ^\.github/workflows/

      # ------------------------
      # YAML linting for GitHub workflows
      # ------------------------
      - id: yamllint
        name: yamllint (github workflows)
        args: [-c, .github/.yamllint]
        files: (^\.github/workflows/.*\.(ya?ml)$|^\.github/actions/.*\.(ya?ml)$)

  # ------------------------
  # GitHub Actions checks
  # ------------------------
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.8
    hooks:
      - id: actionlint
        name: actionlint (github workflows)
        files: (^\.github/workflows/.*\.(ya?ml)$)

  # ------------------------
  # GitHub JSON & project validation
  # ------------------------
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.1
    hooks:
      - id: check-dependabot
        name: Check Dependabot configuration
        description: Validates .github/dependabot.yml.
        args: [--verbose]
        # The `files` regex ensures the hook only runs on this specific file.
        files: ^\.github/dependabot\.yml$
      - id: check-github-workflows
        name: Check GitHub Workflows
        description: Validates all yaml files in .github/workflows.
        args: [--verbose]
        # The `files` regex targets all YAML files
        #  within the workflows directory.
        files: ^\.github/workflows/.*\.ya?ml$
      - id: check-gitlab-ci
        name: Check GitLab CI Configuration
        description: Validates the .gitlab-ci.yml file.
        args: [--verbose]
        # The `files` regex targets the GitLab CI configuration file.
        files: ^\.gitlab-ci\.ya?ml$
      - id: check-taskfile
        name: Check Taskfile Configuration
        description: Validates the configuration for Taskfile.
        args: [--verbose]
        # The `files` regex targets the Taskfile configuration file.
        files: (?i)taskfile\.ya?ml$

  # ------------------------
  # Secrets Detection
  # ------------------------
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.0
    hooks:
      - id: gitleaks
        args: [--config, .github/config/gitleaks.toml]

  # ------------------------
  # pyproject.toml validation
  # ------------------------
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml

  # ------------------------
  # Pre-commit meta checks
  # ------------------------
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  # ----------------------------------------------------
  # 2. General Spelling Check (Crucial for scripts/comments)
  # ----------------------------------------------------
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.2.1
    hooks:
      - id: cspell # Spell check changed files
      - id: cspell # Spell check the commit message
        name: check commit message spelling
        args:
          - --no-must-find-files
          # - --no-progress
          # - --no-summary
          - --files
          - .git/COMMIT_EDITMSG
        stages: [commit-msg]
        always_run: true # This might not be necessary.
