---
# SPDX-License-Identifier: EUPL-1.2
# yamllint disable-line rule:line-length
# SPDX-FileCopyrightText: 2023-present J端rgen M端lbert <juergen.muelbert@gmail.com>
# yamllint disable-line rule:line-length
# Source: https://github.com/jmuelbert/jm-bde/blob/main/workflow-templates/assets/mkdocs/mkdocs.yml
# See: https://www.mkdocs.org/user-guide/configuration/
# yaml-language-server: $schema=https://www.schemastore.org/mkdocs-1.6.json

# --- Project Information ---
site_name: jm-dev-tools
site_url: https://io.github.org/jmuelbert/jm-dev-tools/
site_description: >-
  A modern Python project template with comprehensive tooling.
# Repository
repo_name: jmuelbert/jm-dev-tools
repo_url: https://github.com/jmuelbert/jm-dev-tools/
edit_uri: blob/main/docs/
# Copyright
copyright: Copyright &copy; 2025 - now J端rgen M端lbert

# --- Configuration ---
docs_dir: docs
site_dir: site

# --- Theme Configuration ---
theme:
  name: material
  language: en
  logo: assets/images/jm-py-logo.svg
  favicon: assets/images/jm-py-logo.svg
  custom_dir: docs/.overrides

  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - search.suggest
    - toc.follow

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  extra_css:
    - css/custom.css

  icon:
    repo: fontawesome/brands/github-alt
    logo: assets/images/jm-py-logo.svg

  font:
    text: Roboto
    code: Roboto Mono

# --- Plugins ---
plugins:
  # Built-in
  search:
    lang:
      - en
      - de
      - es
      - it
      - zh
  awesome-pages: {}
  section-index: {}
  glightbox: {}
  include-markdown: {}
  mike:
    alias_type: copy
  # mkdocstrings:
  #   default_handler: python
  #   paths: [src]
  #   options:
  #     show_source: false
  #     show_root_heading: true
  #     show_object_full_path: false
  #     show_category_heading: true
  #     show_bases: true
  #     show_submodules: true
  #     show_signature: true
  #     show_signature_annotations: true
  #     heading_level: 2
  #     separate_signature: true
  #     filters: ["!^_"]
  i18n:
    docs_structure: folder
    fallback_to_default: true
    reconfigure_material: true
    reconfigure_search: true
    languages:
      - locale: en
        default: true
        name: English
        build: true
        site_name: My Project Documentation
      - locale: de
        name: Deutsch
        build: true
  git-revision-date-localized:
    type: date
    strict: false
    # Required for blog plugin's generated indices
    fallback_to_build_date: true
    exclude:
      - blog/**/*

# --- Markdown Extensions ---
markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      line_spans: __span
      pygments_lang_class: true
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

# Customization
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmuelbert
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/jm-bde/

watch:
  - mkdocs.yml
  - docs/

# Page tree
nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
  - User Guide:
      - user-guide/index.md
  - Developer Guide:
      - developer-guide/index.md
      - Security: developer-guide/security.md
  - Api-Reference: api-reference.md
  - Community:
      - Code of Conduct: community/code_of_conduct.md
      - Contributing: community/contributing.md
      - FAQ: community/faq.md
  - About:
      - about/index.md
      - Changelog: about/changelog.md
