---
# SPDX-License-Identifier: EUPL-1.2
# yamllint disable-line rule:line-length
# SPDX-FileCopyrightText: 2025-present J√ºrgen M√ºlbert <juergen.muelbert@gmail.com>

name: Documentation Deployment

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths:
      - docs/**
      - CHANGELOG.md
      - .github/CONTRIBUTING.md
      - .github/CODE_OF_CONDUCT.md
      - mkdocs.yml
      - .github/workflows/docs-deploy.yml

  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # For pushing to the gh-pages branch
      pages: write # Required for deploying to GitHub Pages
      id-token: write # Required for OIDC authentication with GitHub Page

    steps:
      - name: üîí Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: üß∞ Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      - name: üîß Install Astral uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: üìù Deploy Docs with mike
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              VERSION="${GITHUB_REF_NAME}"
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
              VERSION="dev"
          else
              echo "Unsupported ref: ${GITHUB_REF_NAME}"
              exit 0
          fi

          uv venv
          uv sync --extra dev
          uv run mike deploy "$VERSION" --push --update-aliases latest
          uv run mike set-default latest || echo "No 'latest' alias yet"

  verify:
    needs: [build-and-deploy]
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: üîí Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit
      - name: ‚úÖ Verify Workflow Completion
        uses: re-actors/alls-green@2765efec08f0fd63e83ad900f5fd75646be69ff6 # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
