---
# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: 2025-present JÃ¼rgen MÃ¼lbert <juergen.muelbert@outlook.de>

name: Stale Issues and Pull Requests

on:
  schedule:
    - cron: 30 1 * * * # Run at 01:30 UTC daily

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: ðŸ”’ Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76
        with:
          egress-policy: audit

      - name: ðŸ“Š Process Stale Issues and PRs
        uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
        with:
          stale-issue-message: This issue hasn't had recent activity.
          close-issue-message: Closing due to inactivity.
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: priority-high,security,pinned
